apiVersion: v1
kind: Service
metadata:
  name: webbackend
  labels:
    app: webbackend
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: webbackend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "webbackend"
  replicas: 2
  selector:
    matchLabels:
      app: webbackend
  template:
    metadata:
      labels:
        app: webbackend
    spec:
      containers:
      - name: webbackend
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-0
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: web-0
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-1
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: web-1
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
