apiVersion: v1
kind: Service
metadata:
  name: webfront
  labels:
    app: webfront
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: webfront
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfront-deployment
  labels:
    app: webfront
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webfront
  template:
    metadata:
      labels:
        app: webfront
    spec:
      containers:
      - name: webfront
        image: nginx:1.14.2
        ports:
        - containerPort: 80